apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-storage.yaml

helmCharts:
  - name: vault
    includeCRDs: false
    valuesInline:
      server:
        standalone:
          enabled: true
        extraContainers:
          - name: unsealer
            image: vault-init:snapshot
            imagePullPolicy: Never
            env:
              - name: DEBUG
                value: "true"
      injector:
        enabled: false
    releaseName: vault
    version: 0.25.0
    repo: https://helm.releases.hashicorp.com
