---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault:secret-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault:create-secrets
subjects:
  - kind: ServiceAccount
    name: vault
roleRef:
  kind: Role
  name: vault:secret-manager
  apiGroup: rbac.authorization.k8s.io
